# Generated by Django 3.1.1 on 2021-09-04 13:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacton',
            fields=[
                ('unique_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('transaction_number', models.CharField(max_length=100, unique=True)),
                ('transaction_status', models.PositiveSmallIntegerField(choices=[(1, 'PENDING'), (2, 'COMPLETED'), (3, 'CLOSE')])),
                ('remarks', models.CharField(max_length=250)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.branchmaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.companyledgermaster')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.departmentmaster')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLineItem',
            fields=[
                ('unique_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('required_on_date', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=100)),
                ('rate_per_unit', models.PositiveIntegerField()),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 'KG'), (2, 'METRE')])),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.articlemaster')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.colormaster')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transacton')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_quantity', models.DecimalField(decimal_places=2, max_digits=100)),
                ('net_quantity', models.DecimalField(decimal_places=2, max_digits=100)),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 'KG'), (2, 'METRE')])),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.articlemaster')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.colormaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.companyledgermaster')),
                ('linr_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transactionlineitem')),
            ],
        ),
    ]
